import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@assets/styles/global.scss';
import './ShopLayout.scss';
import ShopHeader from '@shopComponents/ShopHeader/ShopHeader';
import ShopFooter from '@shopComponents/ShopFooter/ShopFooter';
import ScrollToTopButton from '@shopComponents/ScrollToTopButton/ScrollToTopButton';
import CartStrip from '@shopComponents/CartStrip/CartStrip';
import ZustangState from '@shopComponents/ZustangState/ZustangState';
import { cookies } from 'next/headers';
import { getServerSession } from 'next-auth';
import SessionProvider from '@commonComponents/SessionProvider/SessionProvider';
import { getCity } from '@fetch/city/getCity';
import { authOptions } from './api/auth/[...nextauth]/handler';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const city = (await getCity()).city;

  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <ZustangState
        products={city.products}
        cartCookie={cookies().get('obed_cart')?.value || ''}
      />
      <body className={montserrat.className}>
        <div className="shop-layout">
          <SessionProvider
            session={session}
            baseUrl="http://localhost:3000"
            basePath="/api/auth"
          >
            <ShopHeader city={city} />
          </SessionProvider>
          <main className="shop-layout__page">{children}</main>
          {/* <ShopFooter /> */}
        </div>
        <ScrollToTopButton />
        <CartStrip />
      </body>
    </html>
  );
}
