version: "3"
services:
  obed_db:
    container_name: obed_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=obed_admin
      - POSTGRES_PASSWORD=NijO9IdBZgKjRvA
      - POSTGRES_DB=obed_db
    image: postgres:15.4-alpine3.17
    networks:
      - app-network

  nestjs:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - obed_db
    volumes:
      - ./backend:/app # Связывает текущую папку с проектом NestJS с /app в контейнере

  nextjs:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - obed_db
    volumes:
      - ./frontend:/app # Связывает текущую папку с проектом NestJS с /app в контейнере

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - nestjs
      - nextjs

networks:
  app-network:
    driver: bridge
