import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@assets/styles/global.scss';
import './ShopLayout.scss';
import ShopHeader from '@shopComponents/ShopHeader/ShopHeader';
import ScrollToTopButton from '@shopComponents/ScrollToTopButton/ScrollToTopButton';
import CartStrip from '@shopComponents/CartStrip/CartStrip';
import ZustangState from '@shopComponents/ZustangState/ZustangState';
import { cookies } from 'next/headers';
import { getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]/handler';
import { redirect } from 'next/navigation';
import { fetchData } from '@fetch/fetchData';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cityResponse = await fetchData.city.getCurrent();
  if (!cityResponse) {
    redirect('http://demo.obedaet-test.ru');
  }
  const city = cityResponse.city;
  const session = await getServerSession(authOptions);

  return (
    <html lang="ru">
      <ZustangState
        products={city.products}
        cartCookie={cookies().get('obed_cart')?.value || ''}
      />
      <body className={montserrat.className}>
        <div className="shop-layout">
          <ShopHeader
            session={session}
            city={city}
            isAdmin={cityResponse.isAdminOrSecret}
          />
          <main className="shop-layout__page">{children}</main>
        </div>
        <ScrollToTopButton />
        <CartStrip />
      </body>
    </html>
  );
}
