import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@assets/styles/global.scss';
import './AdminLayout.scss';
import { getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]/handler';
import { redirect } from 'next/navigation';
import { fetchData } from '@fetch/fetchData';
import StyledComponentsRegistry from '@commonComponents/StyledComponentsRegistry';
import { Layout } from 'antd';
import Content from '@adminComponents/Antd/Content';
import AntdSider from '@adminComponents/Antd/Sider';
import AdminMenu from '@adminComponents/Antd/AdminMenu';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cityResponse = await fetchData.city.getCurrent();
  if (!cityResponse) {
    redirect('http://demo.obedaet-test.ru');
  }
  if (!cityResponse.isAdminOrSecret) {
    redirect('/');
  }
  const city = cityResponse.city;

  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <StyledComponentsRegistry>
          <Layout>
            <AntdSider
              breakpoint="md"
              collapsedWidth="0"
              zeroWidthTriggerStyle={{ top: '0' }}
            >
              <div className="demo-logo-vertical" />
              <AdminMenu city={city} />
            </AntdSider>
            <Layout>
              <Content>
                <div className="admin-layout">
                  <main className="admin-layout__page">{children}</main>
                </div>
              </Content>
            </Layout>
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
