import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@assets/styles/global.scss';
import './AdminLayout.scss';
import { getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]/handler';
import { redirect } from 'next/navigation';
import { fetchData } from '@fetch/fetchData';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cityResponse = await fetchData.city.getCurrent();
  if (!cityResponse) {
    redirect('http://demo.obedaet-test.ru');
  }
  if (!cityResponse.isAdminOrSecret) {
    redirect('/');
  }
  const city = cityResponse.city;
  const session = await getServerSession(authOptions);

  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <div className="admin-layout">
          <main className="admin-layout__page">{children}</main>
        </div>
      </body>
    </html>
  );
}
