import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@assets/styles/global.scss';
import './AdminLayout.scss';
import { redirect } from 'next/navigation';
import { fetchData } from '@fetch/fetchData';
import StyledComponentsRegistry from '@commonComponents/StyledComponentsRegistry';
import AdminClientLayout from '@adminComponents/AdminClientLayout/AdminClientLayout';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cityResponse = await fetchData.city.getCurrent();
  if (!cityResponse) {
    redirect('http://demo.obedaet-test.ru');
  }
  if (!cityResponse.isAdminOrSecret) {
    redirect('/');
  }
  const city = cityResponse.city;

  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <StyledComponentsRegistry>
          <AdminClientLayout cityFromProps={city}>{children}</AdminClientLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
